export const MOVIES_ACTION_TYPES = {
  SET_ALL_MOVIES: "SET_ALL_MOVIES",
  SET_SEARCH_MOVIES: "SET_SEARCH_MOVIES",
  SET_LIKED_MOVIES: "SET_LIKED_MOVIES",
  SET_DISLIKED_MOVIES: "SET_DISLIKED_MOVIES",
  ADD_LIKED_MOVIE: "ADD_LIKED_MOVIE",
  ADD_DISLIKED_MOVIE: "ADD_DISLIKED_MOVIE",
}